
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    # volumes:
    #   - ./frontend/src:/app/src
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/mydb
      - SECRET_KEY=d90dfb7c775c97480d86f1ff15fcc95353dd00c9fe2fcd233878e27c172365f165a25d866c223ac4cc07e777265aa3d566e619df872b81380a4615f714a006e2fbffde2d48a79de7765e24e8816e8718e7398bed107e5baa35baa6fe27d7f8b26d55b4a76581dc17b5349014f09700ca909569954c2319134740a2398c6901c1c7172f25a374649a6a9fdd4dd4a99fa5f8f07f52cfcac323f6cfb93e6cb03a0c7b5f5688aea511d12ad927a37d38ff1f16638707c058c092f2e848c76ef3641cef1e6870594d54eb5af3a8ba7adc23922af79a6c2caf76918b5dd081f0656550dea3c3f1575d76a06b1fd53b255c35b87ecc9acfa8d3155408bea9f9c3a43165
    depends_on:
      - db
    volumes:
      - ./backend/src:/usr/src/app/src

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
